<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwxtnmM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwxtnmM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPwxtnmM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPwxtnmM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPwxtnmM\App_KernelDevDebugContainer([
    'container.build_hash' => 'PwxtnmM',
    'container.build_id' => '8fe41d32',
    'container.build_time' => 1681291637,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwxtnmM');
